from prime_number_table import PrimeNumberGenerator

prime_number_table_multiplication = PrimeNumberGenerator()
prime_number_table_multiplication.create_list(10)
print(prime_number_table_multiplication.prime_list)
