from prime_number_table import Multiplication

prime_number_table_multiplication = Multiplication()
prime_number_table_multiplication.createMatrix(10)
print(prime_number_table_multiplication.prime_list)
